### ISSUE TITLE
Simplify image structure

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-dockerimages#146]
Our number of images has grown, leading to long build times. We can simplify it a bit: 
- [x] Move the CLI features into `capella/base` and `t4c/client/base`, deprecate `capella/cli` and `t4c/client/cli`.
- [x] Move the readonly features into `capella/base` as "preparation script", deprecate `capella/readonly`
- [x] Move backup and exporter features to `t4c/client/base`, deprecate `t4c/client/backup` and `t4c/client/exporter`.

**Comment by amolenaar** [comment]
* What do you envision with a "preparation script"?
* What kind of syntax are you after for the t4c/client/base image? `docker run -e... t4c/client/base backup`? E.i. check the first command argument. If it's either `backup` or `export`, run the designated scripts, else execute the way we currently do.

**Comment by MoritzWeber0** [comment]
> * What do you envision with a "preparation script"?

The remote image executes Python & shell scripts which are located in `/opt/setup`. This enabled defining a runtime script in the Base image. If you start the `capella/remote` image, we could check for the environment variables. If they are defined, we execute the read-only script. Otherwise not. However, it's a bit more difficult for the `readonly` image as it requires ease, which we don't want to have in `capella/base`. Maybe remove the intermedia ease image and merge it with the read-only image.

> * What kind of syntax are you after for the t4c/client/base image? `docker run -e... t4c/client/base backup`? E.i. check the first command argument. If it's either `backup` or `export`, run the designated scripts, else execute the way we currently do.

`docker run -e... t4c/client/base backup` would be a good solution. In Kubernetes, backup could be used as "args" in the container definition. Alternatively, we have a environment variable which contains a ENUM value for the type (backup / export).

**Comment by amolenaar** [comment]
> > * What do you envision with a "preparation script"?
> 
> The remote image executes Python & shell scripts which are located in `/opt/setup`. This enabled defining a runtime script in the Base image. If you start the `capella/remote` image, we could check for the environment variables. If they are defined, we execute the read-only script. Otherwise not. However, it's a bit more difficult for the `readonly` image as it requires ease, which we don't want to have in `capella/base`. Maybe remove the intermedia ease image and merge it with the read-only image.

Not sure what you mean. I'll take a closer look at the docker files.

> > * What kind of syntax are you after for the t4c/client/base image? `docker run -e... t4c/client/base backup`? E.i. check the first command argument. If it's either `backup` or `export`, run the designated scripts, else execute the way we currently do.
> 
> `docker run -e... t4c/client/base backup` would be a good solution. In Kubernetes, backup could be used as "args" in the container definition. Alternatively, we could use a environment variable which contains a ENUM value for the type (backup / export).

I think I like the command style more :smiley:

**Comment by MoritzWeber0** [comment]
> > > * What do you envision with a "preparation script"?
> > 
> > 
> > The remote image executes Python & shell scripts which are located in `/opt/setup`. This enabled defining a runtime script in the Base image. If you start the `capella/remote` image, we could check for the environment variables. If they are defined, we execute the read-only script. Otherwise not. However, it's a bit more difficult for the `readonly` image as it requires ease, which we don't want to have in `capella/base`. Maybe remove the intermedia ease image and merge it with the read-only image.
> 
> Not sure what you mean. I'll take a closer look at the docker files.

Have a look here for the "preparation" scripts: https://github.com/DSD-DBS/capella-dockerimages/blob/main/remote/startup.sh#L18

**Comment by MoritzWeber0** [comment]
The last missing task (removal of the readonly image) has been finished with the release https://github.com/DSD-DBS/capella-dockerimages/releases/tag/v2.0.0.
