### ISSUE TITLE
pyease not found

### ISSUE THREAD

**Issue by ioolkos** [DSD-DBS/capella-dockerimages#25]
Clone command/submodule command cannot update this submodule:

`git submodule update --init --recursive`

```
remote: Repository not found.
fatal: repository 'https://github.com/DSD-DBS/pyease.git/' not found
fatal: clone of 'https://github.com/DSD-DBS/pyease.git' into submodule path 'DS_Capella/capella-dockerimages/ease/pyease' failed
```
What is `pyease` and is it a closed component?
Thanks!

**Comment by MoritzWeber0** [comment]
Hi @ioolkos! Sorry that I only answer so late. I had to fix my Github settings first, I didn't get a notification. 
`pyease` is an internal module that we have developed to work easier with (EASE)[https://www.eclipse.org/ease/] and the (SWTBot)[https://www.eclipse.org/swtbot/] in Capella. Unfortunately, the repository is still private for various reasons. If you do not need EASE, you can simply leave out the command, the rest should continue to work as described.

**Comment by ioolkos** [comment]
@MoritzWeber0 Got it, thanks  for your info!
