### ISSUE TITLE
Bug - model backup job failing - /usr/bin/xvfb-run: 184: /opt/t4c_cli/.venv/bin/backup: not found

### ISSUE THREAD

**Issue by alternone** [DSD-DBS/capella-dockerimages#310]
Backup image: t4c/client/base
as recommended: https://dsd-dbs.github.io/capella-dockerimages/capella/t4c/importer/

job fails within seconds: /usr/bin/xvfb-run: 184: /opt/t4c_cli/.venv/bin/backup: not found

in dockerfile and T4C guide: 
/opt/t4c_cli/ is available but no step to manage venv and also binaries. 

Any recommendations? Do we use the correct backup image? Do we miss a step?

**Comment by MoritzWeber0** [comment]
Hi @alternone. That's a bug in the latest version of the images. There is a bug fix, but was never merged. I'll merge and release it asap.

**Comment by MoritzWeber0** [comment]
New release: https://github.com/DSD-DBS/capella-dockerimages/releases/tag/v2.5.1
