### ISSUE TITLE
Add backups test using GIT_REPO_ENTRYPOINT

### ISSUE THREAD

**Issue by dominik003** [DSD-DBS/capella-dockerimages#88]
It is possible to set an entry point (`GIT_REPO_ENTRYPOINT`) that specifies where the `.aird` file should be placed. Therefore, we should also perform a backup test using this environment variable.

**Comment by MoritzWeber0** [comment]
Read-only sessions have been reworked in https://github.com/DSD-DBS/capella-dockerimages/releases/tag/v2.0.0, so this is no longer relevant.
