### ISSUE TITLE
Build GTK from source

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-dockerimages#89]
The description editor in Capella doesn't work with the latest GTK version. For the installation of older GTK versions we depend on the `focal` apt repository of Ubuntu. Versions for architectures like arm are missing in the registry. It would be nice to build them from source.

**Comment by amolenaar** [comment]
Capella 5.2 and 6.0 is using GTK3. That's not too bad.

**Comment by MoritzWeber0** [comment]
Capella 7.0.0 will have a fixed description editor. Therefore, the issue is no longer needed.
